codecov:
  require_ci_to_pass: true

ignore:
  - "__tests__"
  - "dist"
  - "node_modules"

comment:                  # this is a top-level key
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
