name: 'Setup Buildless'
description: 'Lightning-fast build caching for Github Actions with Buildless'
author: 'Buildless'

branding:
  icon: box
  color: purple

inputs:
  version:
    description: 'Version'
    required: false
    default: 'latest'

  os:
    description: 'OS'
    required: false

  arch:
    description: 'Architecture'
    required: false

  target:
    description: 'Custom install path'
    required: false

  force:
    description: 'Force install'
    required: false

  export_path:
    description: 'Export to Path'
    required: false
    default: 'true'

  custom_url:
    description: 'Custom Download URL'
    required: false

  token:
    description: 'GitHub Token'
    required: false

  agent:
    description: 'Enable Buildless Agent'
    required: false
    default: 'true'

  apikey:
    description: 'Buildless API key'
    required: false

  tenant:
    description: 'Buildless Tenant'
    required: false

  project:
    description: 'Buildless Project'
    required: false

outputs:
  path:
    description: 'Path to Buildless'
  agentConfig:
    description: 'Agent Configuration'

runs:
  using: node20
  main: dist/index.js
  post: dist/cleanup/index.js
