name: "Check: Distribution"

on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  contents: read

jobs:
  check-dist:
    name: "Check: Dist"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: "Setup: Checkout"
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Setup: PNPM"
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8.9.0
      - name: "Setup: Node"
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          cache: pnpm
      - name: "Setup: Install Dependencies"
        id: install
        run: pnpm install && pnpm install -g turbo
      - name: "Build: Bundle"
        id: build
        run: turbo build --token ${{ secrets.BUILDLESS_APIKEY }} --no-daemon --remote-only
      - name: "Check: Compare Expected and Actual Directories"
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi
      - name: "Build: Upload Artifact"
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
